import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    typedocSidebar: [
        'about',
        'authorization',
        {
            type: 'category',
            label: 'API Reference',
            collapsible: false,
            collapsed: false,
            items: [
                {
                    type: 'category',
                    label: 'Classes',
                    collapsible: true,
                    collapsed: false,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'api/classes',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Functions',
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'api/functions',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Interfaces',
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'api/interfaces',
                        },
                    ],
                },
                {
                    type: 'category',
                    label: 'Types',
                    collapsible: true,
                    collapsed: true,
                    items: [
                        {
                            type: 'autogenerated',
                            dirName: 'api/type-aliases',
                        },
                    ],
                },
            ],
        },
    ],
}

export default sidebars
