name: Add new issues to project

on:
    issues:
        types: [opened]

permissions:
    contents: read
    issues: read

jobs:
    add-to-project:
        name: Add issue to project
        runs-on: ubicloud
        timeout-minutes: 5

        steps:
            - name: Add issue to project
              uses: actions/add-to-project@27022a19346d0433f2b9859dd2b69d38f4277808
              with:
                  project-url: https://github.com/orgs/Doist/projects/83
                  github-token: ${{ secrets.HERO_BOARD_PAT }}
